# Generated by Django 5.1 on 2024-09-04 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_escogida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarea',
            name='nivel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
